name = "WinchModels"
uuid = "7dcfa46b-7979-4771-bbf4-0aee0da42e1f"
authors = ["Uwe Fechner <fechner@aenarete.eu> and contributors"]
version = "0.3.2"

[deps]
KiteUtils = "90980105-b163-44e5-ba9f-8b1c83bb0533"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Parameters = "0.12"
KiteUtils = "0.7.8"
julia = "1.10"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ControlPlots = "23c2ee80-7a9e-4350-b264-8e670f12517c"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ControlPlots", "BenchmarkTools", "LaTeXStrings"]
